### ISSUE TITLE
Vragen bij lijst bedreigde soorten bij gebiedsrapport

### ISSUE THREAD

**Issue by wimmassant** [inbo/vlaams-biodiversiteitsportaal#356]
Wanneer ik de lijst van de bedreigede soorten bij het gebiedsrapport bekijk staan hier denk ik ook soorten tussen die niet bedreigd zijn (zelf exoten).
Zie print screen hieronder met soorten zoals Canadese gans en fazant. We moeten duidelijk bepalen vanaf wanneer een soort op de lijst bedreigde soorten komt en dit ook meegeven als info denk ik. 

https://natuurdata.uat.inbo.be/spatial-hub/?ss=1740989793858

![Image](https://github.com/user-attachments/assets/e4bc7df7-fafe-4cec-8958-fe8da676ebcd)

**Comment by StefanVanDyck** [comment]
```
lists:
  url: ''
  #  TODO: causes the portal-full tomcat to hang at startup, spatial-hub blocks on this
  #        and species-lists is no yet serving any requests
  #  url: "${common.protocol}://${common.domain}/species-list"
  threatenedSpeciesUrl: '/ws/speciesList/?isThreatened=eq:true&isAuthoritative=eq:true'
  invasiveSpeciesUrl: '/ws/speciesList/?isInvasive=eq:true&isAuthoritative=eq:true'
  facets: True
  migratoryDR: dr1005
  iconicSpeciesDR: dr781
```
Waarschijnlijk hier mee te maken (in spatial-hub config)
